// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoEc4Z2tL1rSst5RfLSeC_d1cVAXK7zC4',
    appId: '1:536162640690:web:e969410cbb19a267ba2d2b',
    messagingSenderId: '536162640690',
    projectId: 'event-manager-f6862',
    authDomain: 'event-manager-f6862.firebaseapp.com',
    storageBucket: 'event-manager-f6862.firebasestorage.app',
    measurementId: 'G-HHXDJ61SWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOjV1hLWaUC9d-_ah5iqKO9STYzSjWeg',
    appId: '1:536162640690:android:2620bb5d28ed2c9aba2d2b',
    messagingSenderId: '536162640690',
    projectId: 'event-manager-f6862',
    storageBucket: 'event-manager-f6862.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGscTACOrD9uE8RwJHk1EAAEzCTb-w4AQ',
    appId: '1:536162640690:ios:2241d5e921d1aeacba2d2b',
    messagingSenderId: '536162640690',
    projectId: 'event-manager-f6862',
    storageBucket: 'event-manager-f6862.firebasestorage.app',
    androidClientId: '536162640690-5grl1ucmdcvvgia9lr24mscp7mkhijah.apps.googleusercontent.com',
    iosClientId: '536162640690-sa5487oe34kj13hfk05p0obf3nv2q103.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailWags',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoEc4Z2tL1rSst5RfLSeC_d1cVAXK7zC4',
    appId: '1:536162640690:web:be28b2fb0ba222e5ba2d2b',
    messagingSenderId: '536162640690',
    projectId: 'event-manager-f6862',
    authDomain: 'event-manager-f6862.firebaseapp.com',
    storageBucket: 'event-manager-f6862.firebasestorage.app',
    measurementId: 'G-JTNZT7R0HH',
  );
}
